version: '3.8'
services:

  posgres:
    image: postgres:alpine
    container_name: postgresql
    restart: always
    volumes: 
    - postgresql_data:/var/lib/postgresql/data
    env_file:
       - ../.env
    ports:
      - 5432:5432
    networks:
      - backend
 
  bun:
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    restart: always
    container_name: express-app
    depends_on:
      - posgres
    networks:
      - backend
    command:
      - bun install 
      - bun run dev

volumes:
  postgresql_data:
networks:
  backend:
