# JWT Token
## username
## password
## type_key (API|APP)

# Crea un token
POST https://localhost:3000/token/generate-token
Content-Type: application/json
{
  "username":"licha",
  "password":"lichinho",
  "token_type":"API"
}

# Intenta crear un token pero con valores incorrectos
POST https://localhost:3000/token/generate-token
Content-Type: application/json
{
  "username": 2020,
  "password": 10,
  "token_type":"API"
}

# Intenta crear un token 
POST https://localhost:3000/token/generate-token
Content-Type: application/json
{
  "username":"licha",
  "password":"lichinho",
  "token_type":"API"
}

