version: '3.8'
services:

  posgres:
    image: postgres:alpine
    container_name: postgresql
    restart: always
    volumes: 
    - postgresql_data:/var/lib/postgresql/data
    #environment:
    #    POSTGRES_USER: ${POSTGRES_USER}
    #    POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    #    POSTGRES_DB: ${POSTGRES_DB}
    env_file:
       - ../.env
    ports:
      - 5432:5432
    networks:
      - backend

volumes:
  postgresql_data:
networks:
  backend:
